### ISSUE TITLE
This plugin does not work on BungeeCord 1.8

### ISSUE THREAD

**Issue by ClassicOldSong** [Puharesource/ForcedMotd#1]
As the title, I put this plugin in the plugins folder and then start BungeeCord, it generaes the folder "ForcedMOTD" but with NO configure file in it. I created an "config.yml" manually with configuration and then restart BungeeCord, it still doesn't work. Hope you can fix that XD

**Comment by Puharesource** [comment]
Sorry that I did not see this issue prior to this, however, people still seem to be able to use the plugin, till this day, so I'm not too worried about this.
